export const MOVE_SHIP_FORWARD = 'MOVE_SHIP_FORWARD';
export const MOVE_SHIP_BACKWARD = 'MOVE_SHIP_BACKWARD';
export const TURN_SHIP_LEFT = 'TURN_SHIP_LEFT';
export const TURN_SHIP_RIGHT = 'TURN_SHIP_RIGHT';
